name: 'Wipe Github Actions cache'
description: 'Wipes all Github Actions caches for a repository.'
branding:
  icon: 'archive'
  color: 'orange'
inputs:
  github-token:
    description: 'Your GITHUB_TOKEN.'
    required: false
    default: ${{ github.token }}
  dry-run:
    description: 'List caches only, do not clear them.'
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - name: List caches
      id: list-caches
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        ids="$(
          gh api \
            -H 'Accept: application/vnd.github+json' \
            "/repos/${GITHUB_REPOSITORY}/actions/caches" | \
          jq '.actions_caches[].id' |
          tr '\n' ' ' \
        )"
       echo "cache_ids=$(echo $ids)" >> $GITHUB_ENV

    - name: Wipe caches
      id: wipe
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.github-token }}
      run: |
        for id in ${{ env.cache_ids }}; do
          if [[ "${{ inputs.dry-run }}" == 'true' ]]; then
            echo "would delete cache $id using following command:"
            echo gh api \
              --method DELETE \
              -H 'Accept: application/vnd.github+json' \
              "/repos/${GITHUB_REPOSITORY}/actions/caches/$id"
          else
            echo "deleting cache $id"
            gh api \
              --method DELETE \
              -H 'Accept: application/vnd.github+json' \
              "/repos/${GITHUB_REPOSITORY}/actions/caches/$id"
          fi
        done
